---
nodes:
  - address: 192.168.30.2
    user: vagrant
    role: [controlplane, etcd]
  - address: 192.168.30.3
    user: vagrant
    role: [worker]
  - address: 192.168.30.4
    user: vagrant
    role: [worker]

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.12.10-rancher1-1
  kube-controller:
    image: rancher/k8s:v1.12.10-rancher1-1
  scheduler:
    image: rancher/k8s:v1.12.10-rancher1-1
  kubelet:
    image: rancher/k8s:v1.12.10-rancher1-1
  kubeproxy:
    image: rancher/k8s:v1.12.10-rancher1-1