- hosts:
    - local
  become: true
  roles:
    - app.install-docker
    - app.k8s-provision

- hosts: 
    - local
  become: true
  collections:
    - geerlingguy.php_roles
  roles:
    - php
    - role: php_versions
      vars:
        php_version: '7.4'
- hosts:
    - master
  become: true
  roles:
    - andrewrothstein.kubectl
#     - app.install-rke

# - hosts:
#     - rancher
#   become: true
#   roles:
#     - app.start-rancher-server