---
- name: install software-properties-common
  apt:
    name: software-properties-common

- name: add apt repository ondrej/nginx-mainline
  apt_repository:
      repo: ppa:ondrej/nginx-mainline

- name: add apt repository ppa:ondrej/php
  apt_repository:
      repo: ppa:ondrej/php

- name: Update apt-get repo and cache
  apt: 
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: install php7.4
  apt:
    pkg:
      - php7.4-fpm
      - php7.4-bcmath
      - php7.4-bz2
      - php7.4-intl
      - php7.4-gd
      - php7.4-mbstring
      - php7.4-zip
      - php7.4-common
      - php7.4-dom
      - php7.4-xml
      - php7.4-xmlwriter

- name: config user execute php7.4-fpm
  template:
    src: www.j2
    dest: /etc/php/7.4/fpm/pool.d/www.conf

- name: Install low-level utilities
  apt:
    pkg:
      - zip
      - unzip

- name: Download Composer
  script: scripts/install_composer.sh

- name: Move Composer globally
  command: mv composer.phar /usr/local/bin/composer

- name: Set permissions on Composer
  file:
    path: /usr/local/bin/composer
    mode: "a+x"