# sudo apt-get update
# sudo apt -y install software-properties-common
# sudo add-apt-repository ppa:ondrej/nginx-mainline
# sudo add-apt-repository ppa:ondrej/php
# sudo apt-get update
# sudo apt install php7.4-fpm
# sudo apt-get install -y php7.4-{bcmath,bz2,intl,gd,mbstring,mysql,zip,common,dom,xml,xmlwriter}

