---
- name: install compose package
  command: composer install
  args:
    chdir: "{{source_dir}}"

- name: copy env 
  template:
    src: env.j2
    dest: "{{source_dir}}/env."

- name: init env 
  command: php artisan key:generate
  args:
    chdir: "{{source_dir}}"